# Generated by Django 2.1.4 on 2019-01-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogsdata',
            name='borough',
            field=models.CharField(max_length=30),
        ),
    ]
